# Generated by Django 6.0.5 on 2026-06-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwordprogress',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
