# Generated by Django 6.0.5 on 2026-06-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_userwordprogress_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwordprogress',
            name='learned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
