# Generated by Django 5.2.17 on 2026-08-22 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_userwordprogress_learned_at'),
        ('vocabulary', '0002_alter_word_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userwordprogress',
            index=models.Index(fields=['user', 'learned', 'next_review'], name='progress_us_user_id_476e4e_idx'),
        ),
    ]
