# Generated by Django 6.0.5 on 2026-06-03 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('beginner', 'С нуля'), ('elementary', 'Начальный'), ('intermediate', 'Средний')], default='beginner', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('icon', models.CharField(default='📖', max_length=10)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GrammarRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('formula', models.CharField(blank=True, max_length=500)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('korean_examples', models.JSONField(blank=True, default=list)),
                ('russian_examples', models.JSONField(blank=True, default=list)),
                ('order', models.IntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='grammar.grammartopic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
