# Generated by Django 6.0.5 on 2026-06-03 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammartopic',
            name='icon',
            field=models.CharField(default='📖', max_length=50),
        ),
        migrations.CreateModel(
            name='GrammarExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('correct_answer', models.CharField(max_length=500)),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(blank=True, max_length=500)),
                ('option_d', models.CharField(blank=True, max_length=500)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'С нуля'), ('elementary', 'Начальный'), ('intermediate', 'Средний')], default='beginner', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='grammar.grammartopic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
