# Generated by Django 6.0.5 on 2026-06-03 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Выбор ответа'), ('true_false', 'Правда / Ложь'), ('writing', 'Написание')], default='multiple_choice', max_length=20)),
                ('question_korean', models.TextField(blank=True)),
                ('question_russian', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('beginner', 'С нуля'), ('elementary', 'Начальный'), ('intermediate', 'Средний')], default='beginner', max_length=20)),
                ('time_limit', models.IntegerField(default=0, help_text='Seconds (0 = no limit)')),
                ('passing_score', models.IntegerField(default=70, help_text='Percentage to pass')),
                ('order', models.IntegerField(default=0)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='lessons.lesson')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz'),
        ),
    ]
