# Generated by Django 6.0.5 on 2026-06-04 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dailygoal_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='last_active_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
