# Generated by Django 5.2.17 on 2026-08-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_streak_last_active_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='freezes',
            field=models.IntegerField(default=1),
        ),
    ]
