# Generated by Django 5.2.17 on 2026-08-22 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['korean']},
        ),
    ]
